id: PAE4EE59E
initial_creation_type: input
source_metadata:
  Title: Madhyamakahṛdayaḥ
  Editor: Christian Lindtner
  Publisher: The Adyar Library and Research Center
  Place of Publication: Adyar Library, Chennai, India
  Year: '2001'
  prathamaḥ paricchedaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  dvitīyaḥ paricchedaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  tṛtīyaḥ paricchedaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  caturthaḥ paricchedaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  pañcamaḥ paricchedaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  ṣaṣṭhaḥ paricchedaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  saptamaḥ paricchedaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  aṣṭamaḥ paricchedaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  navamaḥ paricchedaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  daśamaḥ paricchedaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  ekādaśaḥ paricchedaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
created_at: '2022-03-08T16:38:13.932060'
last_modified_at: '2022-03-08T16:38:13.932072'
